# Generated by Django 2.2.1 on 2019-05-31 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0070_drop_update_event_and_rename_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='language_code',
            field=models.CharField(default='pt-br', max_length=35),
        ),
    ]
