# Generated by Django 2.2.1 on 2019-06-10 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0071_order_gift_cards'),
        ('order', '0071_auto_20190531_1303'),
    ]

    operations = [
    ]
